import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "NRS - Together We Rise, Together We Prosper.",
  description: "Generated by Dami",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}